[[profile]]
name = "home"

[[profile.output]]
enable = false
search = ["m=0x0AE0", "s=", "v=BOE"]

[[profile.output]]
enable = false
search = ["m=0x058B", "s=", "v=LG Display"]

[[profile.output]]
enable = true
search = ["m=DELL U2715H", "s=GH85D5AL0GXL", "v=Dell Inc."]
mode = "2560x1440@59.951Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=DELL U2715H", "s=GH85D5AL0DWL", "v=Dell Inc."]
mode = "2560x1440@59.951Hz"
position = "2560,0"
scale = 1.0
transform = "normal"
adaptive_sync = false



[[profile]]
name = "nrk"

[[profile.output]]
enable = false
search = ["m=0x0AE0", "s=", "v=BOE"]

[[profile.output]]
enable = true
search = ["m=DELL U2715H", "s=GH85D7420ZVS", "v=Dell Inc."]
mode = "2560x1440@59.951Hz"
position = "2560,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=DELL U2715H", "s=GH85D88J04QL", "v=Dell Inc."]
mode = "2560x1440@59.951Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false


[[profile]]
exec = [ "notify-send Shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"" ]
name = "builtin"

[[profile.output]]
enable = true
search = ["m=0x0AE0", "s=", "v=BOE"]
mode = "2560x1600@60.002Hz"
position = "0,0"
scale = 1
transform = "normal"


[[profile]]
name = "home2"

[[profile.output]]
enable = true
search = ["m=DELL U2715H", "s=GH85D5AL0GXL", "v=Dell Inc."]
mode = "2560x1440@59.951Hz"
position = "1706,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=DELL U2715H", "s=GH85D5AL0DWL", "v=Dell Inc."]
mode = "2560x1440@59.951Hz"
position = "4266,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = false
search = ["m=0x058B", "s=", "v=LG Display"]

[[profile]]
name = "builtin2"

[[profile.output]]
enable = true
search = ["m=0x058B", "s=", "v=LG Display"]
mode = "2560x1440@59.998Hz"
position = "0,0"
scale = 1.5
transform = "normal"
adaptive_sync = false

# [[profile]]
#     name = "laptop"
#     [[profile.output]]
#     enable = true
#     search = ["m=0x0AE0", "s=", "v=BOE"]
#     mode = "2560x1600@60.002Hz"
#     position = "0,0"
#     scale = 1.59765625
#     transform = "normal"
#     adaptive_sync = false
